import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>ValiDate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen'>
        <div className='m-auto h-full flex justify-center items-center'>
          <p className='text-red-700 text-3xl font-bold'>ValiDate</p>
        </div>
      </main>
    </>
  )
}
